config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :users
  resources :lab_reports
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lab_report.rb
class LabReport < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { maximum: 250 }
  validates :description, presence: true, length: { maximum: 500 }
  validates :grade, presence: true, inclusion: { in: %w[A B C D E F FX], message: "must be a valid ECTS grade" }
end

app/models/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lab_reports
  validates :last_name, presence: true, length: { maximum: 100 }
  validates :first_name, presence: true, length: { maximum: 100 }
  validates :email, presence: true, length: { maximum: 150 }, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lab_reports_controller.rb
class LabReportsController < ApplicationController
  before_action :set_lab_report, only: [:show, :edit, :update, :destroy]

  def index
    @lab_reports = LabReport.all
  end

  def show
  end

  def new
    @lab_report = LabReport.new
  end

  def create
    @lab_report = LabReport.new(lab_report_params)
    if @lab_report.save
      redirect_to @lab_report, notice: 'Lab report was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @lab_report.update(lab_report_params)
      redirect_to @lab_report, notice: 'Lab report was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @lab_report.destroy
    redirect_to lab_reports_path, notice: 'Lab report was successfully destroyed.'
  end

  private

  def set_lab_report
    @lab_report = LabReport.find(params[:id])
  end

  def lab_report_params
    params.require(:lab_report).permit(:title, :description, :grade, :user_id)
  end
end

app/controllers/users_controller.rb
# app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lab_reports_helper.rb
module LabReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lab_reports/_form.html.erb
<%= form_with(model: lab_report, local: true) do |form| %>
  <% if lab_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lab_report.errors.count, "error") %> prohibited this lab report from being saved:</h2>

      <ul>
        <% lab_report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, placeholder: "Title" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, placeholder: "This description from you report"%>
  </div>

  <div class="field">
    <%= form.label :grade %>
    <%= form.text_field :grade, placeholder: "Format: A B C D E F FX" %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, placeholder: "User ID" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lab_reports/edit.html.erb
<h1>Edit Lab Report</h1>

<%= render 'form', lab_report: @lab_report %>

<%= link_to 'Show', @lab_report %> |
<%= link_to 'Back', lab_reports_path %>

app/views/lab_reports/index.html.erb
<h1>Lab Reports</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Grade</th>
    <th>User</th>
    <th>User_ID</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @lab_reports.each do |lab_report| %>
    <tr>
      <td><%= lab_report.title %></td>
      <td><%= lab_report.description %></td>
      <td><%= lab_report.grade %></td>
      <td><%= lab_report.user.first_name %></td>
      <td><%= lab_report.user.id %></td>
      <td><%= link_to 'Show |', lab_report %></td>
      <td><%= link_to 'Edit |', edit_lab_report_path(lab_report) %></td>
      <td><%= link_to 'Destroy', lab_report, data: { method: :delete, confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'New Lab Report', new_lab_report_path %>

app/views/lab_reports/new.html.erb
<h1>New Lab Report</h1>

<%= render 'form', lab_report: @lab_report %>

<%= link_to 'Back', lab_reports_path %>

app/views/lab_reports/show.html.erb
<h1><%= @lab_report.title %></h1>

<p><strong>Description:</strong> <%= @lab_report.description %></p>
<p><strong>Grade:</strong> <%= @lab_report.grade %></p>
<p><strong>User:</strong> <%= @lab_report.user.first_name %></p>

<%= link_to 'Edit', edit_lab_report_path(@lab_report) %> |
<%= link_to 'Back', lab_reports_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LabApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav>
    <ul>
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Lab_report', lab_reports_path %></li>
      <li><%= link_to 'Users', users_path %></li>
    </ul>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcome to Laboratory reports App</h1>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>User_ID</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
      <td><%= user.id %></td>
      <td><%= link_to 'Show |', user %></td>
      <td><%= link_to 'Edit |', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, data: { method: :delete, confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1><%= @user.first_name %> <%= @user.last_name %></h1>

<p><strong>Email:</strong> <%= @user.email %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>